"""initial migration

Revision ID: 273499e3b2be
Revises: 
Create Date: 2025-11-01 04:29:22.098751+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '273499e3b2be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_rifa',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('valor_boleta', sa.Integer(), nullable=False),
    sa.Column('total_recaudo', sa.Integer(), nullable=True),
    sa.Column('rake', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('fondo_premios', sa.Integer(), nullable=True),
    sa.Column('premio_por_ganador', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('loterias',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('frecuencia', sa.String(), nullable=True),
    sa.Column('url_resultados', sa.String(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=32), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('rol', sa.Enum('jugador', 'admin', 'operador', name='user_roles'), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('rifas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('loteria_id', sa.UUID(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('numero_ganadores', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'activa', 'cerrada', 'cancelada', name='rifa_states'), nullable=True),
    sa.Column('reglas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_boletas', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_rifa.id'], ),
    sa.ForeignKeyConstraint(['loteria_id'], ['loterias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rifas_fecha_fin'), 'rifas', ['fecha_fin'], unique=False)
    op.create_table('transacciones',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'refunded', name='trans_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rifa_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('comprado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('disponible', 'vendido', 'ganador', 'anulado', name='ticket_states'), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('transaccion_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['rifa_id'], ['rifas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ganadores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('monto_ganado', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), nullable=True),
    sa.Column('referencia_pago', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ganadores')
    op.drop_table('tickets')
    op.drop_table('transacciones')
    op.drop_index(op.f('ix_rifas_fecha_fin'), table_name='rifas')
    op.drop_table('rifas')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('loterias')
    op.drop_table('categoria_rifa')
    # ### end Alembic commands ###
